### PR TITLE
Offload layers to GPU based on new model size estimates

### LINKED ISSUE #1303: Memory required to run differs from expectation
After discussing internally, it was suggested that as long as we have enough total memory across ram and vram, the model should load. Layers are loaded into main memory then offloaded into vram. So I tried with different memory sizes and number of attached T4 cards with 16-ish GB vram each. 

When there is 16 GB RAM and 4x T4, adding up to 76GB, I get a timeout: `Error: timed out waiting for llama runner to start`. 

I get the same error with 30GB RAM, and 60GB RAM. Its not until i go to the next threshold (100 GB) with the 4x T4 that it loads correctly. 

We need to clarify how much memory is required to run models. This is easy where we started on Apple Silicon because there is one number. But more complicated on Nvidia.

### LINKED ISSUE #1374: Out of memory error on model that previously worked fine after update to version 0.1.13
I configured a model to run entirely in VRAM using the following Modelfile:

```
FROM deepseek-coder:33b-instruct-q5_K_S

PARAMETER num_gpu 65
PARAMETER num_ctx 2048
```
I had no issues with running this, it would use about 22GB of my 4090's 24GB VRAM without issue. It would generate responses very quickly which was very helpful for getting quick answers to short coding queries.

However, yesterday I updated Ollama (to 0.1.13), and now I cannot run the same model. I get an out of memory error, despite the model not needing more than 22.5GB (according to the logs below).

I run Ollama on a headless linux server, so there are no other applications using the GPU.

Was there an update that changes how much VRAM Ollama allocates to make it need more than before? Is there a way to configure Ollama so that it behaves the same way as before?

EDIT: Reverting back to ollama version 0.1.11 resolves the issue for now.

Error:
```
Dec 04 16:28:20 osm-server ollama[528776]: llm_load_tensors: offloaded 65/65 layers to GPU
Dec 04 16:28:20 osm-server ollama[528776]: llm_load_tensors: VRAM used: 21741.89 MiB
Dec 04 16:28:23 osm-server ollama[528776]: ....................................................................................................
Dec 04 16:28:23 osm-server ollama[528776]: llama_new_context_with_model: n_ctx      = 2048
Dec 04 16:28:23 osm-server ollama[528776]: llama_new_context_with_model: freq_base  = 100000.0
Dec 04 16:28:23 osm-server ollama[528776]: llama_new_context_with_model: freq_scale = 0.25
Dec 04 16:28:24 osm-server ollama[528776]: llama_kv_cache_init: offloading v cache to GPU
Dec 04 16:28:24 osm-server ollama[528776]: llama_kv_cache_init: offloading k cache to GPU
Dec 04 16:28:24 osm-server ollama[528776]: llama_kv_cache_init: VRAM kv self = 496.00 MiB
Dec 04 16:28:24 osm-server ollama[528776]: llama_new_context_with_model: kv self size  =  496.00 MiB
Dec 04 16:28:24 osm-server ollama[528776]: llama_build_graph: non-view tensors processed: 1430/1430
Dec 04 16:28:24 osm-server ollama[528776]: llama_new_context_with_model: compute buffer total size = 273.07 MiB
Dec 04 16:28:24 osm-server ollama[528776]: llama_new_context_with_model: VRAM scratch buffer: 270.00 MiB
Dec 04 16:28:24 osm-server ollama[528776]: llama_new_context_with_model: total VRAM used: 22507.89 MiB (model: 21741.89 MiB, context: 766.00 MiB)
Dec 04 16:28:24 osm-server ollama[600735]: {"timestamp":1701707304,"level":"INFO","function":"main","line":2917,"message":"HTTP server listening","hostname":"127.0.0.1","port":57264}
Dec 04 16:28:24 osm-server ollama[600735]: {"timestamp":1701707304,"level":"INFO","function":"log_server_request","line":2478,"message":"request","remote_addr":"127.0.0.1","remote_port":46990,"status":200,"method":"HEAD","path":"/","params":{}}
Dec 04 16:28:24 osm-server ollama[528776]: 2023/12/04 16:28:24 llama.go:493: llama runner started in 4.401485 seconds
Dec 04 16:28:24 osm-server ollama[528776]: CUDA error 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:5884: out of memory
Dec 04 16:28:24 osm-server ollama[528776]: current device: 0
Dec 04 16:28:25 osm-server ollama[528776]: 2023/12/04 16:28:25 llama.go:436: 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:5884: out of memory
Dec 04 16:28:25 osm-server ollama[528776]: current device: 0
Dec 04 16:28:25 osm-server ollama[528776]: 2023/12/04 16:28:25 llama.go:510: llama runner stopped successfully
Dec 04 16:28:25 osm-server ollama[528776]: [GIN] 2023/12/04 - 16:28:25 | 200 |  6.468638351s |       127.0.0.1 | POST     "/api/generate"
```

### LINKED ISSUE #1413: OOM Error on Bad CUDA Driver
**Ollama version**: 0.1.1
**Reproduction**:
- `nvidia-smi`
  ```
  Failed to initialize NVML: Driver/library version mismatch
  NVML library version: 535.129
  ```
- Run server
  ```
  IP='0.0.0.0'
  PORT='11434'
  EXE='bin/ollama'
  ARGS='serve'
  ENV="OLLAMA_HOST=$IP:$PORT'"
  CMD="$ENV $EXE $ARGS"
  echo Running $CMD
  eval $CMD
  ```

- Try embedding a slightly long payload   
  ```
  import requests
  response = requests.post('http://localhost:11434/api/embeddings', json={
      'model': 'llama2:latest',
      'prompt': 'Here is an article about llamas...'*30
  })
  ```

- Error
  ```
  CUDA error 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml/ggml-cuda.cu:4856: out of memory
  ```
- Logs
  ```
  {"timestamp":1701923173,"level":"INFO","function":"main","line":1192,"message":"system info","n_threads":32,"total_threads":64,"system_info":"AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | "}
  llama.cpp: loading model from [REDACTED]
  llama_model_load_internal: format     = ggjt v3 (latest)
  llama_model_load_internal: n_vocab    = 32000
  llama_model_load_internal: n_ctx      = 2048
  llama_model_load_internal: n_embd     = 4096
  llama_model_load_internal: n_mult     = 256
  llama_model_load_internal: n_head     = 32
  llama_model_load_internal: n_head_kv  = 32
  llama_model_load_internal: n_layer    = 32
  llama_model_load_internal: n_rot      = 128
  llama_model_load_internal: n_gqa      = 1
  llama_model_load_internal: rnorm_eps  = 5.0e-06
  llama_model_load_internal: n_ff       = 11008
  llama_model_load_internal: freq_base  = 10000.0
  llama_model_load_internal: freq_scale = 1
  llama_model_load_internal: ftype      = 2 (mostly Q4_0)
  llama_model_load_internal: model size = 7B
  llama_model_load_internal: ggml ctx size =    0.08 MB
  llama_model_load_internal: using CUDA for GPU acceleration
  llama_model_load_internal: mem required  = 4013.73 MB (+ 1024.00 MB per state)
  llama_model_load_internal: offloading 0 repeating layers to GPU
  llama_model_load_internal: offloaded 0/35 layers to GPU
  llama_model_load_internal: total VRAM used: 384 MB
  llama_new_context_with_model: kv self size  = 1024.00 MB
  ```

- Fix: Hide GPU with ` CUDA_VISIBLE_DEVICES=''`

### LINKED ISSUE #1516: Memory error
Lot of user don't understand they are facing a memory error.
It could be nice to explain in the error message that it is a memory error.

Error: llama runner process has terminated

Could be replace by:

Error: Llama process ran out of memory.

Or

Error, Ollama could not run the model because it ran out of memory.

### LINKED ISSUE #1534: macOS M2 32 GB -- processing failed
I get error message:
"Error: llama runner process has terminated"

Does that mean it run out of memory?

Is it possible to make it smaller?

### LINKED ISSUE #1566: Error: llama runner exited, you may not have enough available memory to run this model
Hi,

When I have run a modell and try to communicate with it, I always get same response, no matter which model (or small or big)...
'
Error: llama runner exited, you may not have enough available memory to run this model  
'

Any clues on this one?

My host is running ubuntu 20.04 on proxmox with approx 56 gb memory free, nvidia m40 24 gb gpu
'
free
              total        used        free      shared  buff/cache   available
Mem:       58212660      641572    54462900        5692     3108188    56950236
Swap:       8388604           0     8388604
'

'
nvidia-smi 
Sat Dec 16 19:39:44 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla M40 24GB                 Off | 00000000:01:00.0 Off |                    0 |
| N/A   37C    P8              16W / 250W |      0MiB / 23040MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
'

Seems ollama finds the gpu:
journalctl:
`
Dec 16 18:30:05 tesla ollama[2245]: 2023/12/16 18:30:05 llama.go:300: 22939 MB VRAM available, loading up to 150 GPU layers
Dec 16 18:30:05 tesla ollama[2245]: 2023/12/16 18:30:05 llama.go:436: starting llama runner
Dec 16 18:30:05 tesla ollama[2245]: 2023/12/16 18:30:05 llama.go:494: waiting for llama runner to start responding
Dec 16 18:30:05 tesla ollama[2245]: ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
Dec 16 18:30:05 tesla ollama[2245]: ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
Dec 16 18:30:05 tesla ollama[2245]: ggml_init_cublas: found 1 CUDA devices:
Dec 16 18:30:05 tesla ollama[2245]:   Device 0: Tesla M40 24GB, compute capability 5.2
Dec 16 18:30:05 tesla ollama[2326]: {"timestamp":1702751405,"level":"INFO","function":"main","line":2652,"message":"build info","build":441,"commit":"948ff1>
Dec 16 18:30:05 tesla ollama[2326]: {"timestamp":1702751405,"level":"INFO","function":"main","line":2655,"message":"system info","n_threads":8,"n_threads_ba>
Dec 16 18:30:05 tesla ollama[2245]: llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from /usr/share/ollama/.ollama/models/blobs>
--- ---
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: ggml ctx size =    0.12 MiB
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: using CUDA for GPU acceleration
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: mem required  =   70.43 MiB
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: offloading 32 repeating layers to GPU
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: offloading non-repeating layers to GPU
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: offloaded 33/33 layers to GPU
Dec 16 18:31:49 tesla ollama[2245]: llm_load_tensors: VRAM used: 3577.56 MiB
`

Loading a modell works fine, but error comes when trying to communicate, happens with any modell, even the smallest.
Error: llama runner exited, you may not have enough available memory to run this model  

journalctl:
' 
 Dec 16 18:31:50 tesla ollama[2245]: ..................................................................................................
Dec 16 18:31:50 tesla ollama[2245]: llama_new_context_with_model: n_ctx      = 4096
Dec 16 18:31:50 tesla ollama[2245]: llama_new_context_with_model: freq_base  = 10000.0
Dec 16 18:31:50 tesla ollama[2245]: llama_new_context_with_model: freq_scale = 1
Dec 16 18:31:51 tesla ollama[2245]: llama_kv_cache_init: VRAM kv self = 2048.00 MB
Dec 16 18:31:51 tesla ollama[2245]: llama_new_context_with_model: KV self size  = 2048.00 MiB, K (f16): 1024.00 MiB, V (f16): 1024.00 MiB
Dec 16 18:31:51 tesla ollama[2245]: llama_build_graph: non-view tensors processed: 676/676
Dec 16 18:31:51 tesla ollama[2245]: llama_new_context_with_model: compute buffer total size = 291.32 MiB
Dec 16 18:31:51 tesla ollama[2245]: llama_new_context_with_model: VRAM scratch buffer: 288.00 MiB
Dec 16 18:31:51 tesla ollama[2245]: llama_new_context_with_model: total VRAM used: 5913.57 MiB (model: 3577.56 MiB, context: 2336.00 MiB)
Dec 16 18:31:51 tesla ollama[2588]: {"timestamp":1702751511,"level":"INFO","function":"main","line":3035,"message":"HTTP server listening","hostname":"127.0>
Dec 16 18:31:51 tesla ollama[2588]: {"timestamp":1702751511,"level":"INFO","function":"log_server_request","line":2596,"message":"request","remote_addr":"12>
Dec 16 18:31:51 tesla ollama[2245]: 2023/12/16 18:31:51 llama.go:508: llama runner started in 2.201689 seconds
Dec 16 18:31:51 tesla ollama[2245]: [GIN] 2023/12/16 - 18:31:51 | 200 |  2.311479662s |       127.0.0.1 | POST     "/api/generate"
Dec 16 18:32:14 tesla ollama[2588]: {"timestamp":1702751534,"level":"INFO","function":"log_server_request","line":2596,"message":"request","remote_addr":"12>
Dec 16 18:32:14 tesla ollama[2245]: 2023/12/16 18:32:14 llama.go:577: loaded 0 images
**Dec 16 18:32:14 tesla ollama[2245]: cuBLAS error 15 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:8448**
Dec 16 18:32:14 tesla ollama[2245]: current device: 0
**Dec 16 18:32:14 tesla ollama[2245]: GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:8448: !"cuBLAS error"**
Dec 16 18:32:14 tesla ollama[2245]: 2023/12/16 18:32:14 llama.go:451: signal: aborted (core dumped)
Dec 16 18:32:14 tesla ollama[2245]: 2023/12/16 18:32:14 llama.go:525: llama runner stopped successfully
Dec 16 18:32:14 tesla ollama[2245]: [GIN] 2023/12/16 - 18:32:14 | 200 |  601.813679ms |       127.0.0.1 | POST     "/api/generate"
'
 

Full log:
https://www.evernote.com/shard/s16/sh/6d2eab19-c11f-7cf4-148c-9a5cd04dc944/Zwy3R7zsW8TvzDquK5Devnpko4BPwqNquvDt4nHLGCiecB_luwmk3sH8ug

The gpu is a bit dated, so it might miss some features newer nvidia cards have.  It is a affordable option to run with a lot of vram so would be nice if it was supported.

When running ComfyUI i have to start with --disable-cuda-malloc. 

Regards,

Bård Ove Myhr

### LINKED ISSUE #1576: 70b model not working on apple silicon
memory is 48 GB
pulling model is fine
ollama run llama2:70b

error is
```
Error: llama runner process has terminated
```

### LINKED ISSUE #1627: Can't run dolphin-mixtral, llama runner process has terminated
Hi,
I have trouble running dolphin mixtral using ollama

When I type `ollama run dolphin-mixtral` the message "llama runner process has terminated" appears

This is the log:
```
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  =  512.00 MiB, K (f16):  256.00 MiB, V (f16):  256.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Pro
ggml_metal_init: picking default device: Apple M1 Pro
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/var/folders/tw/8r367x6x1t12cqcm0w9fhcgh0000gn/T/ollama2368397414/llama.cpp/gguf/build/metal/bin/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M1 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 22906.50 MB
ggml_metal_init: maxTransferRate               = built-in GPU
llama_new_context_with_model: compute buffer total size = 319.22 MiB
llama_new_context_with_model: max tensor size =   102.55 MiB
ggml_metal_add_buffer: allocated 'data            ' buffer, size = 16384.00 MiB, offs =            0
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  8935.19 MiB, offs =  17072324608, (25320.81 / 21845.34)ggml_metal_add_buffer: warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =   512.03 MiB, (25832.84 / 21845.34)ggml_metal_add_buffer: warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =   316.05 MiB, (26148.89 / 21845.34)ggml_metal_add_buffer: warning: current allocated size is greater than the recommended max working set size
ggml_metal_graph_compute: command buffer 4 failed with status 5
GGML_ASSERT: /Users/jmorgan/workspace/ollama/llm/llama.cpp/gguf/ggml-metal.m:2353: false
2023/12/20 11:45:01 llama.go:451: signal: abort trap
2023/12/20 11:45:01 llama.go:459: error starting llama runner: llama runner process has terminated
2023/12/20 11:45:01 llama.go:525: llama runner stopped successfully
[GIN] 2023/12/20 - 11:45:01 | 500 | 25.934369375s |       127.0.0.1 | POST     "/api/generate"
```

I would greatly appreciate any help! :)

Thanks

### LINKED ISSUE #1636: Error : llama runner process has terminated , on running mistral "ollama run mistral"
I have a MacBook Air M1. Earlier the mistral model used to run flawlessly , upon the latest update of both ollama and mistral model , the model refuses to run.
Any Explaination or troubleshooting ?

### LINKED ISSUE #1674: Out of memory at v0.1.17, revert to v0.1.14 OK. Related to "context" size
image

Context:
Windows Docker Desktop
WSL2
NVIDIA RTX3060
Running ollama docker with GPU enabled

What I think the key differences in the log is that the Ollama v0.1.17 gives extra context for 1116.00 MiB
`2023-12-22 21:45:16 llama_new_context_with_model: total VRAM used: 5207.27 MiB (model: 4091.27 MiB, context: 1116.00 MiB)`
while 0.1.14 gives 156.00 MiB
`2023-12-22 21:37:37 llama_new_context_with_model: total VRAM used: 4247.27 MiB (model: 4091.27 MiB, context: 156.00 MiB)`

Also v0.1.17 allocate `30/33 layers to GPU`
while v0.1.14 allocate `30/35 layers to GPU`
for the same model

Here are more logs
### v0.1.17
```
2023-12-22 21:45:07 llama_model_loader: - type  f32:   65 tensors
2023-12-22 21:45:07 llama_model_loader: - type q5_K:  193 tensors
2023-12-22 21:45:07 llama_model_loader: - type q6_K:   33 tensors
2023-12-22 21:45:07 llm_load_vocab: mismatch in special tokens definition ( 243/32256 vs 237/32256 ).
2023-12-22 21:45:07 llm_load_print_meta: format           = GGUF V3 (latest)
2023-12-22 21:45:07 llm_load_print_meta: arch             = llama
2023-12-22 21:45:07 llm_load_print_meta: vocab type       = BPE
2023-12-22 21:45:07 llm_load_print_meta: n_vocab          = 32256
2023-12-22 21:45:07 llm_load_print_meta: n_merges         = 31757
2023-12-22 21:45:07 llm_load_print_meta: n_ctx_train      = 16384
2023-12-22 21:45:07 llm_load_print_meta: n_embd           = 4096
2023-12-22 21:45:07 llm_load_print_meta: n_head           = 32
2023-12-22 21:45:07 llm_load_print_meta: n_head_kv        = 32
2023-12-22 21:45:07 llm_load_print_meta: n_layer          = 32
2023-12-22 21:45:07 llm_load_print_meta: n_rot            = 128
2023-12-22 21:45:07 llm_load_print_meta: n_gqa            = 1
2023-12-22 21:45:07 llm_load_print_meta: f_norm_eps       = 0.0e+00
2023-12-22 21:45:07 llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
2023-12-22 21:45:07 llm_load_print_meta: f_clamp_kqv      = 0.0e+00
2023-12-22 21:45:07 llm_load_print_meta: f_max_alibi_bias = 0.0e+00
2023-12-22 21:45:07 llm_load_print_meta: n_ff             = 11008
2023-12-22 21:45:07 llm_load_print_meta: n_expert         = 0
2023-12-22 21:45:07 llm_load_print_meta: n_expert_used    = 0
2023-12-22 21:45:07 llm_load_print_meta: rope scaling     = linear
2023-12-22 21:45:07 llm_load_print_meta: freq_base_train  = 100000.0
2023-12-22 21:45:07 llm_load_print_meta: freq_scale_train = 0.25
2023-12-22 21:45:07 llm_load_print_meta: n_yarn_orig_ctx  = 16384
2023-12-22 21:45:07 llm_load_print_meta: rope_finetuned   = unknown
2023-12-22 21:45:07 llm_load_print_meta: model type       = 7B
2023-12-22 21:45:07 llm_load_print_meta: model ftype      = Q5_K - Medium
2023-12-22 21:45:07 llm_load_print_meta: model params     = 6.74 B
2023-12-22 21:45:07 llm_load_print_meta: model size       = 4.46 GiB (5.68 BPW) 
2023-12-22 21:45:07 llm_load_print_meta: general.name     = deepseek-ai_deepseek-coder-6.7b-instruct
2023-12-22 21:45:07 llm_load_print_meta: BOS token        = 32013 '<｜begin▁of▁sentence｜>'
2023-12-22 21:45:07 llm_load_print_meta: EOS token        = 32021 '<|EOT|>'
2023-12-22 21:45:07 llm_load_print_meta: PAD token        = 32014 '<｜end▁of▁sentence｜>'
2023-12-22 21:45:07 llm_load_print_meta: LF token         = 126 'Ä'
2023-12-22 21:45:07 llm_load_tensors: ggml ctx size =    0.11 MiB
2023-12-22 21:45:07 llm_load_tensors: using CUDA for GPU acceleration
2023-12-22 21:45:07 llm_load_tensors: mem required  =  471.22 MiB
2023-12-22 21:45:07 llm_load_tensors: offloading 30 repeating layers to GPU
2023-12-22 21:45:07 llm_load_tensors: offloaded 30   layers to GPU
2023-12-22 21:45:07 llm_load_tensors: VRAM used: 4091.27 MiB
2023-12-22 21:45:15 ..................................................................................................
2023-12-22 21:45:15 llama_new_context_with_model: n_ctx      = 2048
2023-12-22 21:45:15 llama_new_context_with_model: freq_base  = 100000.0
2023-12-22 21:45:15 llama_new_context_with_model: freq_scale = 0.25
2023-12-22 21:45:16 llama_kv_cache_init: VRAM kv self = 960.00 MB
2023-12-22 21:45:16 llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
2023-12-22 21:45:16 llama_build_graph: non-view tensors processed: 676/676
2023-12-22 21:45:16 llama_new_context_with_model: compute buffer total size = 159.19 MiB
2023-12-22 21:45:16 llama_new_context_with_model: VRAM scratch buffer: 156.00 MiB
2023-12-22 21:45:16 llama_new_context_with_model: total VRAM used: 5207.27 MiB (model: 4091.27 MiB, context: 1116.00 MiB)
2023-12-22 21:45:17 {"timestamp":1703256317,"level":"INFO","function":"main","line":3097,"message":"HTTP server listening","port":"55075","hostname":"127.0.0.1"}
2023-12-22 21:45:17 {"timestamp":1703256317,"level":"INFO","function":"log_server_request","line":2608,"message":"request","remote_addr":"127.0.0.1","remote_port":48006,"status":200,"method":"HEAD","path":"/","params":{}}
2023-12-22 21:45:17 2023/12/22 14:45:17 llama.go:512: llama runner started in 11.612463 seconds
2023-12-22 21:45:17 2023/12/22 14:45:17 llama.go:581: loaded 0 images
2023-12-22 21:45:17 map[frequency_penalty:0 image_data:[] main_gpu:0 mirostat:0 mirostat_eta:0.1 mirostat_tau:5 n_keep:0 n_predict:-1 penalize_nl:true presence_penalty:0 prompt:You are a sophisticated, accurate, and modern AI programming assistant Stop your response with ###END###
2023-12-22 21:45:17 ### Request:
2023-12-22 21:45:17 Python code to get current time and put it as a string with format something like "yyyy-mm-dd hh:mm"
2023-12-22 21:45:17 ### Code: **[Stream Issue] ollama: llama runner exited, you may not have enough available memory to run this model** Stop your response with ###END###
2023-12-22 21:45:17 ### Request:
2023-12-22 21:45:17 Python code to get current time and put it as a string with format something like "yyyy-mm-dd hh:mm"
2023-12-22 21:45:17 ### Code: repeat_last_n:64 repeat_penalty:1.1 seed:-1 stop:[###END###] stream:true temperature:0.5 tfs_z:1 top_k:40 top_p:0.9 typical_p:1]
2023-12-22 21:45:17 
2023-12-22 21:45:17 CUDA error 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:6600: out of memory
2023-12-22 21:45:17 current device: 0
2023-12-22 21:45:17 GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:6600: !"CUDA error"
2023-12-22 21:45:18 2023/12/22 14:45:18 llama.go:455: 2 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:6600: out of memory
2023-12-22 21:45:18 current device: 0
2023-12-22 21:45:18 GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:6600: !"CUDA error"
2023-12-22 21:45:18 2023/12/22 14:45:18 llama.go:529: llama runner stopped successfully
2023-12-22 21:45:18 [GIN] 2023/12/22 - 14:45:18 | 200 | 14.020072602s |      172.17.0.1 | POST     "/api/chat"
```

### v0.1.14
```
2023-12-22 21:37:31 llama_model_loader: - type  f32:   65 tensors
2023-12-22 21:37:31 llama_model_loader: - type q5_K:  193 tensors
2023-12-22 21:37:31 llama_model_loader: - type q6_K:   33 tensors
2023-12-22 21:37:31 llm_load_vocab: mismatch in special tokens definition ( 243/32256 vs 237/32256 ).
2023-12-22 21:37:31 llm_load_print_meta: format           = GGUF V3 (latest)
2023-12-22 21:37:31 llm_load_print_meta: arch             = llama
2023-12-22 21:37:31 llm_load_print_meta: vocab type       = BPE
2023-12-22 21:37:31 llm_load_print_meta: n_vocab          = 32256
2023-12-22 21:37:31 llm_load_print_meta: n_merges         = 31757
2023-12-22 21:37:31 llm_load_print_meta: n_ctx_train      = 16384
2023-12-22 21:37:31 llm_load_print_meta: n_embd           = 4096
2023-12-22 21:37:31 llm_load_print_meta: n_head           = 32
2023-12-22 21:37:31 llm_load_print_meta: n_head_kv        = 32
2023-12-22 21:37:31 llm_load_print_meta: n_layer          = 32
2023-12-22 21:37:31 llm_load_print_meta: n_rot            = 128
2023-12-22 21:37:31 llm_load_print_meta: n_gqa            = 1
2023-12-22 21:37:31 llm_load_print_meta: f_norm_eps       = 0.0e+00
2023-12-22 21:37:31 llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
2023-12-22 21:37:31 llm_load_print_meta: f_clamp_kqv      = 0.0e+00
2023-12-22 21:37:31 llm_load_print_meta: f_max_alibi_bias = 0.0e+00
2023-12-22 21:37:31 llm_load_print_meta: n_ff             = 11008
2023-12-22 21:37:31 llm_load_print_meta: rope scaling     = linear
2023-12-22 21:37:31 llm_load_print_meta: freq_base_train  = 100000.0
2023-12-22 21:37:31 llm_load_print_meta: freq_scale_train = 0.25
2023-12-22 21:37:31 llm_load_print_meta: n_yarn_orig_ctx  = 16384
2023-12-22 21:37:31 llm_load_print_meta: rope_finetuned   = unknown
2023-12-22 21:37:31 llm_load_print_meta: model type       = 7B
2023-12-22 21:37:31 llm_load_print_meta: model ftype      = mostly Q5_K - Medium
2023-12-22 21:37:31 llm_load_print_meta: model params     = 6.74 B
2023-12-22 21:37:31 llm_load_print_meta: model size       = 4.46 GiB (5.68 BPW) 
2023-12-22 21:37:31 llm_load_print_meta: general.name     = deepseek-ai_deepseek-coder-6.7b-instruct
2023-12-22 21:37:31 llm_load_print_meta: BOS token        = 32013 '<｜begin▁of▁sentence｜>'
2023-12-22 21:37:31 llm_load_print_meta: EOS token        = 32021 '<|EOT|>'
2023-12-22 21:37:31 llm_load_print_meta: PAD token        = 32014 '<｜end▁of▁sentence｜>'
2023-12-22 21:37:31 llm_load_print_meta: LF token         = 126 'Ä'
2023-12-22 21:37:31 llm_load_tensors: ggml ctx size =    0.11 MiB
2023-12-22 21:37:31 llm_load_tensors: using CUDA for GPU acceleration
2023-12-22 21:37:31 llm_load_tensors: mem required  =  471.22 MiB
2023-12-22 21:37:31 llm_load_tensors: offloading 30 repeating layers to GPU
2023-12-22 21:37:31 llm_load_tensors: offloaded 30/35 layers to GPU
2023-12-22 21:37:31 llm_load_tensors: VRAM used: 4091.27 MiB
2023-12-22 21:37:37 ..................................................................................................
2023-12-22 21:37:37 llama_new_context_with_model: n_ctx      = 2048
2023-12-22 21:37:37 llama_new_context_with_model: freq_base  = 100000.0
2023-12-22 21:37:37 llama_new_context_with_model: freq_scale = 0.25
2023-12-22 21:37:37 llama_new_context_with_model: kv self size  = 1024.00 MiB
2023-12-22 21:37:37 llama_build_graph: non-view tensors processed: 676/676
2023-12-22 21:37:37 llama_new_context_with_model: compute buffer total size = 159.07 MiB
2023-12-22 21:37:37 llama_new_context_with_model: VRAM scratch buffer: 156.00 MiB
2023-12-22 21:37:37 llama_new_context_with_model: total VRAM used: 4247.27 MiB (model: 4091.27 MiB, context: 156.00 MiB)
2023-12-22 21:37:37 {"timestamp":1703255857,"level":"INFO","function":"main","line":3038,"message":"HTTP server listening","hostname":"127.0.0.1","port":62142}
2023-12-22 21:37:37 {"timestamp":1703255857,"level":"INFO","function":"log_server_request","line":2599,"message":"request","remote_addr":"127.0.0.1","remote_port":49528,"status":200,"method":"HEAD","path":"/","params":{}}
2023-12-22 21:37:38 2023/12/22 14:37:37 llama.go:506: llama runner started in 8.410558 seconds
2023-12-22 21:37:42 {"timestamp":1703255862,"level":"INFO","function":"log_server_request","line":2599,"message":"request","remote_addr":"127.0.0.1","remote_port":49528,"status":200,"method":"POST","path":"/completion","params":{}}
2023-12-22 21:42:42 2023/12/22 14:42:42 llama.go:449: signal: killed
2023-12-22 21:42:42 2023/12/22 14:42:42 llama.go:523: llama runner stopped successfully
```

### LINKED ISSUE #1703: Error: llama runner process has terminated. when running dolphin-mixtral
when i run ollama run dolphin-mixtral it gives the error Error: llama runner process has terminated.

### LINKED ISSUE #1812: IMPROVEMENT: Proper calcuation of the KV cache size inside of gpu::NumGPU() instead of the 3/4 magic number...
See: https://github.com/jmorganca/ollama/issues/1800#issuecomment-1878955910

Feel free to pull out the stuff from that thread - it's only in there as I did quite a lot of research on this to try to figure out the OOM errors.

### LINKED ISSUE #1837: Ollama crashes quite often for  Fedora 39 with NVIDIA T1200 Laptop GPU
Hello, 

When I use ollama  with NVIDIA T1200 Laptop GPU on Fedora 39, it crashes quite often regardless what models I am running.  Is there any way to troubleshoot this issue? 

Here is the output of `nvidia-smi`

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA T1200 Laptop GPU        Off | 00000000:01:00.0  On |                  N/A |
| N/A   44C    P8               6W /  60W |    303MiB /  4096MiB |      7%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3280      G   /usr/libexec/Xorg                           115MiB |
|    0   N/A  N/A      4776    C+G   ...seed-version=20240105-201042.648000      177MiB |
+---------------------------------------------------------------------------------------+

```

### LINKED ISSUE #1838: Cuda Error with 2GB VRAM: `Error: Post "http://127.0.0.1:11434/api/generate": EOF`
Hello everyone, in Ollama version 0.1.18, I'm encountering the error "Error: Post "http://127.0.0.1:11434/api/generate": EOF" when starting Ollama with any model. I think it depends of cuda...
[logs_ollama.txt](https://github.com/jmorganca/ollama/files/13852832/logs_ollama.txt)

### PR DESCRIPTION
**Pull request by jmorganca**
This PR fixes a large number of crashes and "out of memory" errors related to VRAM allocation, by using a more accurate estimation of how much memory is required to run a model with a given context size.

Models such as `mixtral` will now run on lower end hardware that would previously before, even if defaulting to the CPU is required. Also, more layers are loaded to Nvidia GPUs which should result in a speedup on Linux.

Details:
- VRAM estimation now accounts for the kv cache and tensor graph (which can grow to GiBs for large context sizes)
- On macOS, Ollama will now run in CPU mode, even on Apple Silicon (`arm64`) if the GPU doesn't have enough VRAM. Models such as `mixtral`, `llama2:70b`, etc will now work (perhaps slowly) instead of crashing
- On Linux, the number of layers to be offloaded to the GPU now accounts for the kv cache which is also partially offloaded

Todo in a follow up:
- Handle smaller batch sizes as mention in #1812
- Still seeing some errors with very large context sizes (64k, 128k)
- Limit `num_ctx` to what the model is trained on

Fixes #1838
Fixes #1812
Fixes #1516 
Fixes #1674
Fixes #1374
Fixes #1534
Fixes #1303
Fixes #1413
Fixes #1636
Fixes #1837
Fixes #1627
Fixes #1566
Fixes #1576
Fixes #1703

### CODE REVIEW

File: gpu/gpu_darwin.go [hunk 1]
```diff
@@ -6,18 +6,30 @@ import "C"
...
-	"github.com/jmorganca/ollama/api"
+	"github.com/pbnjay/memory"
 )
 
 // CheckVRAM returns the free VRAM in bytes on Linux machines with NVIDIA GPUs
 func CheckVRAM() (int64, error) {
-	// TODO - assume metal, and return free memory?
-	return 0, nil
+	if runtime.GOARCH == "amd64" {
+		return 0, nil
```
Comment (BruceMacD) [inline gpu/gpu_darwin.go:15]:
```suggestion
		// gpu not supported, this may not be metal
		return 0, nil
```

File: llm/gguf.go [hunk 2]
```diff
@@ -272,14 +272,49 @@ func (llm *ggufModel) Decode(rso *readSeekOffset) error {
...
 
-	v := value.(uint32)
-	return int64(v)
+	return value.(uint32)
+}
+
+func (llm *ggufModel) NumHead() uint32 {
+	value, exists := llm.kv[fmt.Sprintf("%s.attention.head_count", llm.ModelFamily())]
+	if !exists {
+		return 0
```
Comment (BruceMacD) [inline llm/gguf.go:287]: Logging something in these `!exists` cases will help us debug problems in the future.

File: llm/llm.go [hunk 3]
```diff
@@ -40,57 +37,110 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
-		case "47B":
-			requiredMemory = 48 * format.GigaByte
-		case "65B", "70B":
-			requiredMemory = 64 * format.GigaByte
-		case "180B":
-			requiredMemory = 128 * format.GigaByte
-			f16Multiplier = 4
-		}
+	if opts.NumCtx < 4 {
+		opts.NumCtx = 4
```
Comment (BruceMacD) [inline llm/llm.go:41]: what makes this the minimum?

File: gpu/gpu_darwin.go [hunk 4]
```diff
@@ -6,18 +6,30 @@ import "C"
 import (
 	"runtime"
 
-	"github.com/jmorganca/ollama/api"
+	"github.com/pbnjay/memory"
 )
 
 // CheckVRAM returns the free VRAM in bytes on Linux machines with NVIDIA GPUs
 func CheckVRAM() (int64, error) {
```
Comment (BruceMacD) [inline gpu/gpu_darwin.go:13]: You can remove the `error` returned by the function, it's not returned anymore

File: llm/llm.go [hunk 5]
```diff
@@ -40,57 +37,110 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
+	fmt.Println("head_kv", ggml.NumHeadKv())
+	fmt.Println("gqa", ggml.NumGQA())
+
+	available, _ := gpu.CheckVRAM()
+
+	// For now assume filesize = model size
+	// TODO: use actual model size
+	requiredModel := ggml.Size
+
+	// fp16 k,v matrices each require = n_ctx * n_layer * n_embd / n_head * n_head_kv * 2 bytes each
```
Comment (BruceMacD) [inline llm/llm.go:60]:
```suggestion
	// fp16 k,v matrices each require = n_ctx * n_layer * n_embd / n_head * n_head_kv * 2 bytes each * 2 key and value
```

File: llm/llm.go [hunk 6]
```diff
@@ -40,57 +37,110 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
+	// this amount is the overhead + tensors in memory
+	// TODO: get this from the llama.cpp's graph calcluations instead of
+	// guessing it's ~1/8th of the kv cache times gqa
+	// this is slightly (~25%) higher than what it is in reality
+	// TODO: this needs to account for batch size != 512
+	requiredAlloc := int64(ggml.NumGQA()) * requiredKv / 8
+
+	requiredTotal := requiredModel + requiredKv + requiredAlloc
+
+	fmt.Println("system memory ", available)
```
Comment (BruceMacD) [inline llm/llm.go:72]: nit: would be nice to have the units here (ie: MB)

File: llm/llm.go [hunk 7]
```diff
@@ -40,57 +37,110 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
+	fmt.Println("required model", requiredModel)
+	fmt.Println("required kv", requiredKv)
+	fmt.Println("required alloc", requiredAlloc)
+	fmt.Println("required total", requiredTotal)
+
+	if opts.NumGPU == -1 {
+		opts.NumGPU = int(ggml.NumLayers()) + 1
```
Comment (BruceMacD) [inline llm/llm.go:79]:
```suggestion
		// default to offloading the entire model + gpu back-end
		opts.NumGPU = int(ggml.NumLayers()) + 1
```

File: llm/llm.go [hunk 8]
```diff
@@ -40,57 +37,110 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
-		if ggml.FileType() == "F16" && requiredMemory*f16Multiplier > systemMemory {
-			return nil, fmt.Errorf("F16 model requires at least %s of memory", format.HumanBytes(requiredMemory))
-		} else if requiredMemory > systemMemory {
-			return nil, fmt.Errorf("model requires at least %s of memory", format.HumanBytes(requiredMemory))
+	// decide how many layers to put on the GPU
+	if opts.NumGPU > 0 {
+		switch runtime.GOOS {
+		case "darwin":
+			if requiredTotal > available {
+				fmt.Println("not enough vram available, falling back to CPU only")
```
Comment (BruceMacD) [inline llm/llm.go:87]:
```suggestion
				log.Printf("not enough vram available, %sMB required, falling back to CPU only", requiredTotal)
```
This is probably logged elsewhere, in that case ignore this comment

File: llm/llm.go [hunk 9]
```diff
@@ -40,57 +37,110 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
+				break
+			}
+
+			available -= requiredAlloc
+
+			// fill remaining vram with layers
+			fmt.Println("splitting", available, "into layers")
+			bytesPerLayer := int64((requiredModel + requiredKv) / int64(ggml.NumLayers()))
+			fmt.Println("bytes per layer:", bytesPerLayer)
+			layers := available/bytesPerLayer + 1
```
Comment (BruceMacD) [inline llm/llm.go:116]: why `+1` here?

**Review by BruceMacD — COMMENTED** [review]
this is looking pretty good so far

File: llm/llm.go (hunk 3 above)
Comment (jmorganca) [reply llm/llm.go:41]: Llama.cpp will crash below this number IIRC

File: gpu/gpu_darwin.go (hunk 4 above)
Comment (dhiltgen) [reply gpu/gpu_darwin.go:13]: The code is getting a bit tangled, but the linux/windows variants do return error for CPU scenarios, but it's become pedantic, so I think removing the error return is probably safe, just requires some changes to llm.go and routes.go

Comment (BruceMacD) [reply gpu/gpu_darwin.go:13]: Ah, dang, maybe a different change in that case

File: llm/llm.go [hunk 10]
```diff
@@ -40,57 +37,115 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
+	fmt.Println("head_kv", ggml.NumHeadKv())
+	fmt.Println("gqa", ggml.NumGQA())
+
+	available, _ := gpu.CheckVRAM()
+
+	// For now assume filesize = model size
+	// TODO: use actual model size
+	requiredModel := ggml.Size
+
+	// fp16 k,v matrices each require = n_ctx * n_layer * n_embd / n_head * n_head_kv * 2 bytes each * 2 key and value
```
Comment (jmorganca) [inline llm/llm.go:60]:
```suggestion
	// fp16 k,v matrices require = n_ctx * n_layer * n_embd / n_head * n_head_kv * 2 bytes each * 2 key and value
```

File: gpu/gpu_darwin.go (hunk 4 above)
Comment (jmorganca) [reply gpu/gpu_darwin.go:13]: I'll leave it for this PR but worth revisiting

File: llm/llm.go [hunk 11]
```diff
@@ -40,57 +37,116 @@ func New(workDir, model string, adapters, projectors []string, opts api.Options)
...
+
+			available -= requiredAlloc
+
+			// fill remaining vram with layers
+			log.Println("splitting", available, "of available memory bytes into layers")
+			bytesPerLayer := int64((requiredModel + requiredKv) / int64(ggml.NumLayers()))
+			log.Println("bytes per layer:", bytesPerLayer)
+
+			// leave some room for overhead
+			// available = (available * 9) / 10
```
Comment (BruceMacD) [inline llm/llm.go:121]:
```suggestion
```
looks like this may have been from debugging

File: gpu/gpu.go [hunk 12]
```diff
@@ -133,31 +131,14 @@ func getCPUMem() (memInfo, error) {
...
 	if gpuInfo.FreeMemory > 0 && (gpuInfo.Library == "cuda" || gpuInfo.Library == "rocm") {
-		return int64(gpuInfo.FreeMemory), nil
-	}
-	return 0, fmt.Errorf("no GPU detected") // TODO - better handling of CPU based memory determiniation
-}
+		// allocate 384MiB for llama.cpp overhead (outside of model)
+		overhead := uint64(384 * 1024 * 1024)
+		if gpuInfo.FreeMemory <= overhead {
+			return 0, nil
+		}
```
Comment (dhiltgen) [inline gpu/gpu.go:138]: I'm a little torn.  You put this here because it seems to be GPU specific (doesn't affect mac), but logically it feels to me like it makes more sense in llm.go:New where we're doing all the memory calculations.

**Review by dhiltgen — APPROVED** [review]

File: llm/shim_ext_server.go [hunk 13]
```diff
@@ -72,7 +72,7 @@ func (llm *shimExtServer) llama_server_release_json_resp(json_resp **C.char) {
 	C.dynamic_shim_llama_server_release_json_resp(llm.s, json_resp)
 }
 
-func newDynamicShimExtServer(library, model string, adapters, projectors []string, numLayers int64, opts api.Options) (extServer, error) {
+func newDynamicShimExtServer(library, model string, adapters, projectors []string, opts api.Options) (extServer, error) {
```
Comment (MatthewCash) [inline llm/shim_ext_server.go:75]: Changing the function signature here but not in llm/ext_server_windows.go broke Windows builds.

Comment (jmorganca) [reply llm/shim_ext_server.go:75]: @MatthewCash sorry about that! Should be fixed on `main`

Comment (MatthewCash) [reply llm/shim_ext_server.go:75]: Thank you! 😄

**Comment by deltawi** [comment]
Hey team, how do we get this update ? is this already available through `pip install` ?
