### PR TITLE
better error message when model not found on pull

### LINKED ISSUE #180: When the registry doesn't know of the model/manifest, have a clearer error
I mis-typed the name of the model I wanted to run, and got a JSON-encoded error message:

```
MacBook-Pro-2:~ griscom$ ollama list
NAME                	SIZE  	MODIFIED     
llama2:13b          	7.3 GB	9 hours ago 	
llama2:latest       	3.8 GB	2 days ago  	
nous-hermes:latest  	7.3 GB	23 hours ago	
orca:latest         	1.9 GB	23 hours ago	
wizard-vicuna:latest	7.3 GB	24 hours ago	
MacBook-Pro-2:~ griscom$ ollama run orcq
pulling manifest
Error: stream: pull model manifest: "registry responded with code 404: {\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"manifest unknown\",\"detail\":{\"Tag\":\"latest\"}}]}\n"
MacBook-Pro-2:~ griscom$ 
```

It would be helpful if ollama parsed this error (and others?) to provide a more user-friendly message, e.g. "Unknown model 'orcq'".

### PR DESCRIPTION
**Pull request by BruceMacD**
```
ollama run orca-dne
pulling manifest
Error: pull model manifest: model not found
```

resolves #180

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]

File: server/images.go [hunk 1]
```diff
@@ -738,6 +738,8 @@ func PullModel(name string, regOpts *RegistryOptions, fn func(api.ProgressRespon
 	return nil
 }
 
+var errModelNotFound = fmt.Errorf("model not found")
```
Comment (mxyng) [inline server/images.go:741]: Is there a need to create an error var? I don't see anything using it other than http.StatusNotFound
