### PR TITLE
relay model runner error message to client

### LINKED ISSUE #630: Error: failed to start a llama runner
When I run 

    ollama run mistral

it downloads properly but then fails to run it, with the following error:

    Error: failed to start a llama runner

### PR DESCRIPTION
**Pull request by BruceMacD**
This got missed in the migration to subprocesses. 

Old error displayed in CLI:
```
failed to start llama runner
```

New error (will relay the actual error from the model runner):
```
Error: llama runner failed: out of memory
```

resolves #630

### CODE REVIEW

File: llm/llama.go [hunk 1]
```diff
@@ -306,7 +311,9 @@ func newLlama(model string, adapters []string, runners []ModelRunner, numLayers
 		)
 		cmd.Env = append(os.Environ(), fmt.Sprintf("LD_LIBRARY_PATH=%s", filepath.Dir(runner.Path)))
 		cmd.Stdout = os.Stderr
-		cmd.Stderr = os.Stderr
+		var stderr bytes.Buffer
```
Comment (mxyng) [inline llm/llama.go:314]: `bytes.Buffer` isn't ideal since it can grow infinitely if the subprocess continuously writes to Stderr. Instead, you can create a Writer that checks for error and sends to the error channel.

Something like this:

```go
type StatusWriter struct{}

func (w StatusWriter) Write(b []byte) (int, error) {
  if _, after, ok := bytes.Cut(b, "error:"); ok {
    return 0, fmt.Errorf("runner error: %s", after)
  }

  return nil
}
```

Comment (BruceMacD) [reply llm/llama.go]: Great suggestion thanks, this is much nicer.

File: llm/llama.go [hunk 2]
```diff
@@ -248,6 +248,26 @@ func NumGPU(numLayer, fileSizeBytes int64, opts api.Options) int {
...
+	return &StatusWriter{
+		ErrCh: make(chan error, 1),
+	}
+}
+
+func (w *StatusWriter) Write(b []byte) (int, error) {
+	if _, after, ok := bytes.Cut(b, []byte("error:")); ok {
+		err := fmt.Errorf("llama runner: %s", after)
+		w.ErrCh <- err
+		return os.Stderr.Write(b)
```
Comment (mxyng) [inline llm/llama.go:266]: don't need this. just let it fall through

**Review by mxyng — APPROVED** [review]
